#!/bin/sh
#
# Start gonzales
#

start() {
	printf "Starting gonzales: "
	export DOMAIN_FOLDER=/root
	tmux new-session -d -s gonzales
	tmux send-keys "sleep 5 ; gonzales_bbb" C-m
	tmux detach -s gonzales_bbb
	echo "OK"
}

stop() {
	printf "Stopping gonzales: "
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
